import Head from "next/head";
import styles from "styles/layout.module.css";

const Layout = ({ children, isDay }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>The weather 🌤</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={
        isDay !== undefined
        ? isDay ? {backgroundColor: '#0070f330'} : {backgroundColor: '#7F00FF30'}
        : null
      }>{children}</main>
    </div>
  );
};

export default Layout;
